[tox]
env_list = lint, main

[vars]
src_path = {tox_root}/jubilant_adapters
tests_path = {tox_root}/jubilant_adapters
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
set_env =
    PY_COLORS = 1
    PYTHONPATH = src/
allowlist_externals =
    uv
    uvx

[testenv:format]
description = Apply coding style standards to code
commands_pre =
    uv sync --frozen --dev
commands =
    uvx ruff check  --config pyproject.toml --fix {[vars]all_path}
    uvx ruff format --config pyproject.toml {[vars]all_path}


[testenv:lint]
description = Check code against coding style standards
commands_pre =
    uv sync --frozen --dev
commands =
    uvx codespell --toml {tox_root}/pyproject.toml {[vars]all_path}
    uvx ruff check --config {tox_root}/pyproject.toml {[vars]all_path}
    uvx ruff format --check --config {tox_root}/pyproject.toml --diff {[vars]all_path}
    uv run pyright {[vars]all_path}


[testenv:tests]
description = Run tests
set_env =
    {[testenv]set_env}
    PYTHONPATH = {[vars]src_path}
commands_pre =
    uv sync --frozen --dev
commands =
    uv run coverage run \
        --source={[vars]src_path} \
        -m pytest \
        -vv \
        --tb native \
        -s \
        tests \
        {posargs}
    uv run coverage report